// <auto-generated />

using FallProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace FallProject.Migrations {
    [DbContext(typeof(FallprojectContext))]
    internal class FallprojectContextModelSnapshot : ModelSnapshot {
        protected override void BuildModel(ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion",                 "2.2.0-preview3-35497")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("FallProject.Models.GuildMember", b => {
                                                                      b.Property<decimal>("Id")
                                                                       .ValueGeneratedOnAdd()
                                                                       .HasConversion(new ValueConverter<decimal,
                                                                                          decimal
                                                                                      >(v => default(decimal),
                                                                                        v => default(decimal),
                                                                                        new
                                                                                            ConverterMappingHints(precision: 20,
                                                                                                                  scale
                                                                                                                  : 0)));

                                                                      b.Property<decimal>("GuildId")
                                                                       .HasConversion(new ValueConverter<decimal,
                                                                                          decimal
                                                                                      >(v => default(decimal),
                                                                                        v => default(decimal),
                                                                                        new
                                                                                            ConverterMappingHints(precision: 20,
                                                                                                                  scale
                                                                                                                  : 0)));

                                                                      b.Property<decimal>("UnmuteAt")
                                                                       .HasConversion(new ValueConverter<decimal,
                                                                                          decimal
                                                                                      >(v => default(decimal),
                                                                                        v => default(decimal),
                                                                                        new
                                                                                            ConverterMappingHints(precision: 20,
                                                                                                                  scale
                                                                                                                  : 0)));

                                                                      b.Property<decimal>("Xp")
                                                                       .HasConversion(new ValueConverter<decimal,
                                                                                          decimal
                                                                                      >(v => default(decimal),
                                                                                        v => default(decimal),
                                                                                        new
                                                                                            ConverterMappingHints(precision: 20,
                                                                                                                  scale
                                                                                                                  : 0)));

                                                                      b.HasKey("Id");

                                                                      b.ToTable("GuildMembers");
                                                                  });

            modelBuilder.Entity("FallProject.Models.Message", b => {
                                                                  b.Property<decimal>("Id")
                                                                   .HasConversion(new ValueConverter<decimal, decimal
                                                                                  >(v => default(decimal),
                                                                                    v => default(decimal),
                                                                                    new
                                                                                        ConverterMappingHints(precision: 20,
                                                                                                              scale:
                                                                                                              0)))
                                                                   .HasColumnName("id");

                                                                  b.Property<decimal>("AuthorId")
                                                                   .HasConversion(new ValueConverter<decimal, decimal
                                                                                  >(v => default(decimal),
                                                                                    v => default(decimal),
                                                                                    new
                                                                                        ConverterMappingHints(precision: 20,
                                                                                                              scale:
                                                                                                              0)))
                                                                   .HasColumnName("authorid");

                                                                  b.Property<decimal>("ChannelId")
                                                                   .HasConversion(new ValueConverter<decimal, decimal
                                                                                  >(v => default(decimal),
                                                                                    v => default(decimal),
                                                                                    new
                                                                                        ConverterMappingHints(precision: 20,
                                                                                                              scale:
                                                                                                              0)))
                                                                   .HasColumnName("channelid");

                                                                  b.Property<string>("Content")
                                                                   .IsRequired()
                                                                   .HasColumnName("content");

                                                                  b.Property<string>("EditsAsString");

                                                                  b.Property<decimal>("GuildId")
                                                                   .HasConversion(new ValueConverter<decimal, decimal
                                                                                  >(v => default(decimal),
                                                                                    v => default(decimal),
                                                                                    new
                                                                                        ConverterMappingHints(precision: 20,
                                                                                                              scale:
                                                                                                              0)))
                                                                   .HasColumnName("guildid");

                                                                  b.HasKey("Id");

                                                                  b.ToTable("message");
                                                              });
#pragma warning restore 612, 618
        }
    }
}